/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Producto;
import Modelo.TPV;

/**
 *
 * @author Usuario
 */
public class ClienteVista extends javax.swing.JFrame {

    private TPV terminal;

    /**
     * Creates new form Cliente
     * @param terminal
     */
    public ClienteVista(TPV terminal) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.terminal = terminal;
    }

    public TPV getTerminal() {
        return terminal;
    }

    public void setTerminal(TPV terminal) {
        this.terminal = terminal;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONAR EL TIPO DE CLIENTE");

        btnCF.setText("Consumidor Final");
        btnCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFActionPerformed(evt);
            }
        });

        jButton1.setText("Responsable Inscripto");

        jButton2.setText("Excento");

        jButton3.setText("Monotributista");

        jButton4.setText("No Registrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCF)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFActionPerformed
        // TODO add your handling code here:
        this.getTerminal().getVenta().crearCliente("Consumidor Final");
        VentaPedido ventaPedido = new VentaPedido(this.getTerminal());
        
        ventaPedido.getModeloTablaProducto().getColumnCount();
        
        ventaPedido.getModeloTablaProducto().addColumn("Codigo");
        ventaPedido.getModeloTablaProducto().addColumn("Nombre");
        ventaPedido.getModeloTablaProducto().addColumn("Precio");
        ventaPedido.getModeloTablaProducto().addColumn("Rubro");
        
        for(Producto producto : this.getTerminal().getNegocio().getProductos()){
        Object[] fila = new Object[4];
        fila[0] = producto.getCodigo();
        fila[1] = producto.getNombre();
        fila[2] = producto.getPrecio();
        fila[3] = producto.getRubro().getRubro();
        
        ventaPedido.getModeloTablaProducto().addRow(fila);
        }
        
        ventaPedido.getTablaProducto().setModel(ventaPedido.getModeloTablaProducto());
        
        ventaPedido.getCantidadProducto().setText("0");
        ventaPedido.getTextoAgregado().setText("0");
        
        ventaPedido.getModeloTablaAgregado().getColumnCount();

                ventaPedido.getModeloTablaAgregado().addColumn("Codigo");
                ventaPedido.getModeloTablaAgregado().addColumn("Nombre");
                ventaPedido.getModeloTablaAgregado().addColumn("Precio");
                ventaPedido.getModeloTablaAgregado().addColumn("Incluido");
                ventaPedido.getModeloTablaAgregado().addColumn("Agregado");
                ventaPedido.getTablaAgregado().setModel(ventaPedido.getModeloTablaAgregado());
                
                this.dispose();
    }//GEN-LAST:event_btnCFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
