/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.TPV;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.accessibility.AccessibleContext;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuPrincipal extends  javax.swing.JFrame implements FocusListener{

    private TPV terminal;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(TPV terminal) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.terminal = terminal;
        setTotals();
        this.addFocusListener(this);
        this.setTitle("Bienvenido " + terminal.getEmpleado().getUsuario());
    }
    

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    public TPV getTerminal() {
        return terminal;
    }

    public void setTerminal(TPV terminal) {
        this.terminal = terminal;
    }


    public JMenuItem getCerrarSesion() {
        return cerrarSesion;
    }

    public void setCerrarSesion(JMenuItem cerrarSesion) {
        this.cerrarSesion = cerrarSesion;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantVentLb = new javax.swing.JLabel();
        totalVentasLb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        cerrarSesion.setText("Finalizar Turno");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(cerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalVentasLb)
                    .addComponent(cantVentLb))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cantVentLb)
                .addGap(67, 67, 67)
                .addComponent(totalVentasLb)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
        terminal.finalizarTurno();
        JOptionPane.showMessageDialog(null,"Total Recaudado en el Turno es de $ "+ terminal.totalRecaudadoEnElTurno());
        this.dispose();
       
        
        

    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        terminal.IniciarVenta();
        new ClienteVista(terminal).setVisible(true);
        setTotals();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantVentLb;
    private javax.swing.JMenuItem cerrarSesion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel totalVentasLb;
    // End of variables declaration//GEN-END:variables

    private void setTotals() {
        cantVentLb.setText("Cantidad de ventas: " + terminal.cantidadDeVentasEnElTurno());
        totalVentasLb.setText("Total recaudado: " + terminal.totalRecaudadoEnElTurno());
    }

    @Override
    public void focusGained(FocusEvent e) {
      setTotals();
    }

    @Override
    public void focusLost(FocusEvent e) {
       setTotals();
    }
    

 

}
