/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Agregado;
import Modelo.LineaVenta;
import Modelo.Producto;
import Modelo.TPV;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Usuario
 */
public class VentaPedido extends javax.swing.JFrame {

    private DefaultTableModel modeloTablaProducto = new DefaultTableModel();
    private DefaultTableModel modeloTablaAgregado = new DefaultTableModel();
    private TPV terminal;
    private Producto producto;

    /**
     * Creates new form Venta
     */
    public VentaPedido(TPV terminal) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.terminal = terminal;
    }

    public DefaultTableModel getModeloTablaProducto() {
        return modeloTablaProducto;
    }

    public void setModeloTablaProducto(DefaultTableModel modeloTablaProducto) {
        this.modeloTablaProducto = modeloTablaProducto;
    }

    public DefaultTableModel getModeloTablaAgregado() {
        return modeloTablaAgregado;
    }

    public void setModeloTablaAgregado(DefaultTableModel modeloTablaAgregado) {
        this.modeloTablaAgregado = modeloTablaAgregado;
    }

    public TPV getTerminal() {
        return terminal;
    }

    public void setTerminal(TPV terminal) {
        this.terminal = terminal;
    }

    public JLabel getCantidad() {
        return Cantidad;
    }

    public void setCantidad(JLabel Cantidad) {
        this.Cantidad = Cantidad;
    }

    public JButton getAgregar() {
        return agregar;
    }

    public void setAgregar(JButton agregar) {
        this.agregar = agregar;
    }

    public JButton getAgregarPedido() {
        return agregarPedido;
    }

    public void setAgregarPedido(JButton agregarPedido) {
        this.agregarPedido = agregarPedido;
    }


    public JTextField getCantidadProducto() {
        return cantidadProducto;
    }

    public void setCantidadProducto(JTextField cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }

    public void setCantidad(JTextField cantidad) {
        this.cantidadProducto = cantidad;
    }

    public JButton getEliminar() {
        return eliminar;
    }

    public void setEliminar(JButton eliminar) {
        this.eliminar = eliminar;
    }

    public JButton getFinalizar() {
        return finalizar;
    }

    public void setFinalizar(JButton finalizar) {
        this.finalizar = finalizar;
    }

    public JButton getSalir() {
        return salir;
    }

    public void setSalir(JButton salir) {
        this.salir = salir;
    }

    public JTable getTablaAgregado() {
        return tablaAgregado;
    }

    public void setTablaAgregado(JTable tablaAgregado) {
        this.tablaAgregado = tablaAgregado;
    }

    public JTable getTablaProducto() {
        return tablaProducto;
    }

    public void setTablaProducto(JTable tablaProducto) {
        this.tablaProducto = tablaProducto;
    }

    public JTextField getTextoAgregado() {
        return textoAgregado;
    }

    public void setTextoAgregado(JTextField textoAgregado) {
        this.textoAgregado = textoAgregado;
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }       

    public void limpiarTabla(TableModel tableModel) {

        int cols = tableModel.getColumnCount();

        int fils = tableModel.getRowCount();

        for (int i = 0; i <= fils - 1; i++) {

            for (int j = 1; j <= cols - 1; j++) {
                tableModel.setValueAt("", i, j);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAgregado = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoAgregado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        agregarPedido = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        cantidadProducto = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Pedido");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Rubro"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 170));

        tablaAgregado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Incluido", "Agregado"
            }
        ));
        tablaAgregado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAgregadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAgregado);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 350, 170));

        jLabel3.setText("LISTA DE PRODUCTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        jLabel4.setText("AGREGADOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));
        getContentPane().add(textoAgregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 60, -1));

        jLabel5.setText("Introducir codigo del agregado");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        agregarPedido.setText("Agregar Pedido");
        agregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        getContentPane().add(cantidadProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 40, -1));

        Cantidad.setText("Cantidad");
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:

        TableModel tableModel = this.getTablaAgregado().getModel();

        DefaultTableModel modelo = (DefaultTableModel) this.getTablaAgregado().getModel();
        int filas = this.getTablaAgregado().getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }

        String numCadena2 = this.getTextoAgregado().getText();

        int numEntero2 = Integer.parseInt(numCadena2);

        for (Agregado agregado : this.getProducto().getAgregados()) {
            /*if (agregado.getCodigo() == numEntero2 && !agregado.isHabilitado()) {
                agregado.setHabilitado(true);
            }*/
            this.getTerminal().agregarAgregado(numEntero2, this.getProducto());
            Object[] fila = new Object[5];
            fila[0] = agregado.getCodigo();
            fila[1] = agregado.getNombre();
            fila[2] = agregado.getPrecio();
            fila[3] = agregado.isIncluido();
            fila[4] = agregado.isHabilitado();

            this.getModeloTablaAgregado().addRow(fila);

        }

        this.getTablaAgregado().setModel(this.getModeloTablaAgregado());


    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:

        DefaultTableModel modelo = (DefaultTableModel) this.getTablaAgregado().getModel();
        int filas = this.getTablaAgregado().getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
            
        
        String numCadena2 = this.getTextoAgregado().getText();

        int numEntero2 = Integer.parseInt(numCadena2);

        for (Agregado agregado : this.getProducto().getAgregados()) {
            /*if (agregado.getCodigo() == numEntero2 && agregado.isHabilitado()) {
                agregado.setHabilitado(false);
            }*/
            this.getTerminal().quitarAgregado(numEntero2, this.getProducto());
               Object[] fila = new Object[5];
                    fila[0] = agregado.getCodigo();
                    fila[1] = agregado.getNombre();
                    fila[2] = agregado.getPrecio();
                    fila[3] = agregado.isIncluido();
                    fila[4] = agregado.isHabilitado();

                    this.getModeloTablaAgregado().addRow(fila);
        }

        this.getTablaAgregado().setModel(this.getModeloTablaAgregado());

    }//GEN-LAST:event_eliminarActionPerformed

    private void agregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoActionPerformed
        // TODO add your handling code here:
        String numCadena2 = this.getCantidadProducto().getText();

        int cant = Integer.parseInt(numCadena2);
        
        this.getTerminal().agregarPedido(cant, this.getProducto());


        DefaultTableModel modelo = (DefaultTableModel) this.getTablaAgregado().getModel();
        int filas = this.getTablaAgregado().getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }


    }//GEN-LAST:event_agregarPedidoActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        this.getTerminal().finalizarVenta();

        Comprobante comprobante = new Comprobante(this.getTerminal());

        comprobante.getModeloDescripcio().getColumnCount();
        comprobante.getModeloDescripcio().addColumn("Cantidad");
        comprobante.getModeloDescripcio().addColumn("Descripción");
        comprobante.getModeloDescripcio().addColumn("Precio Unitario");
        comprobante.getModeloDescripcio().addColumn("Total");

        for (LineaVenta lv : this.getTerminal().getVenta().getLineasVentas()) {
            Object[] fila = new Object[4];
            fila[0] = lv.getCantidad();
            fila[1] = lv.getProducto().getNombre();
            fila[2] = lv.getProducto().calcularPrecio();
            fila[3] = lv.getSubTotal();
            
            comprobante.getModeloDescripcio().addRow(fila);

        }
        comprobante.getImporteNeto().setText(String.valueOf(this.getTerminal().getVenta().getNeto()));
        comprobante.getImporteTotal().setText(String.valueOf(this.getTerminal().getVenta().getTotal()));

        comprobante.getDetalleComprobante().setModel(comprobante.getModeloDescripcio());

        
        this.dispose();

    }//GEN-LAST:event_finalizarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void tablaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseClicked
        int seleccion = tablaProducto.rowAtPoint(evt.getPoint());
      //String numCadena = this.getCodigoProducto().getText();
      //int numEntero = Integer.parseInt(numCadena);//transforma el string a  numero

        boolean bandera = false;

            Producto producto = this.getTerminal().ingresarCodigoProducto(seleccion+1);
            if (producto != null) {
                this.setProducto(producto);
                bandera = true;

                for (Agregado agregado : producto.getAgregados()) {
                    Object[] fila = new Object[5];
                    fila[0] = agregado.getCodigo();
                    fila[1] = agregado.getNombre();
                    fila[2] = agregado.getPrecio();
                    fila[3] = agregado.isIncluido();
                    fila[4] = agregado.isHabilitado();

                    this.getModeloTablaAgregado().addRow(fila);
                }

            }
            this.getTablaAgregado().setModel(this.getModeloTablaAgregado());

        
        if (!bandera) {
            ErrorCodigoProducto error = new ErrorCodigoProducto(this, true);
        }
    }//GEN-LAST:event_tablaProductoMouseClicked

    private void tablaAgregadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAgregadoMouseClicked
              int seleccion = tablaProducto.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tablaAgregadoMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregarPedido;
    private javax.swing.JTextField cantidadProducto;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaAgregado;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTextField textoAgregado;
    // End of variables declaration//GEN-END:variables
}
